# Generated by Django 3.2.5 on 2021-07-14 20:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='maintenanceagreement',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 15, 0, 47, 59, 150848), null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceagreement',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 15, 0, 47, 59, 150784), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 0, 47, 59, 139846)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 0, 47, 59, 139846)),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 0, 47, 59, 139846)),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maintenance.tasktypes'),
            preserve_default=False,
        ),
    ]
