# Generated by Django 3.2.5 on 2021-07-17 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20210715_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='material',
        ),
        migrations.AddField(
            model_name='task',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, to='maintenance.Material'),
        ),
        migrations.AlterField(
            model_name='maintenanceagreement',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 17, 20, 45, 3, 773991), null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceagreement',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 17, 20, 45, 3, 773991), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 20, 45, 3, 771991)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 20, 45, 3, 771991)),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 20, 45, 3, 770991)),
        ),
    ]
