# Generated by Django 3.2.5 on 2021-07-18 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20210717_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='coordinates',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceagreement',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 18, 22, 49, 35, 265760), null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceagreement',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 18, 22, 49, 35, 265760), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 22, 49, 35, 264765)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 22, 49, 35, 264765)),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 22, 49, 35, 263766)),
        ),
    ]
